import Head from 'next/head';
import { useRouter } from 'next/router';
import { ReactNode } from 'react';
import styles from './Layout.module.scss';

import { Nunito } from 'next/font/google';
import shortcuts from './Shortcuts';

type Props = {
    children: ReactNode
}

const nunito = Nunito({ subsets: ['latin'] })

export default ({ children }: Props) => {
    const router = useRouter()

    const goToHome = () => router.push('/')

    return (
        <div id={styles.app} className={nunito.className} {...shortcuts()}  >
            <Head>
                <title>GRF Games</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/images/favicon.png" />
            </Head>

            <header className={styles.header}>
                <div className={styles.headerBrand} onClick={goToHome} />
            </header>

            <div className={styles.content}>
                <div className={styles.contentBody}>
                    {children}
                </div>
            </div>
        </div>
    )
}